apiVersion: v1
kind: Service
metadata:
  name: wso2-is-nlb
  namespace: otss
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: wso2-is
    app.kubernetes.io/name: identity-server
  ports:
    - name: https
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: https-redirect
      port: 443
      targetPort: 9443
      protocol: TCP
